GET http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZTMxMWQ2OGVkODkwMDgxOWRkZGJhOSIsImlhdCI6MTY0MjM0MjQ0OH0.JjxkhKpR0pf6jeuvvKJzzD-c1QIiCvZlNAkpip-VdiM

###

GET http://localhost:3001/api/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZTMxMWQ2OGVkODkwMDgxOWRkZGJhOSIsImlhdCI6MTY0MjM0MjQ0OH0.JjxkhKpR0pf6jeuvvKJzzD-c1QIiCvZlNAkpip-VdiM

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZTMxMWQ2OGVkODkwMDgxOWRkZGJhOSIsImlhdCI6MTY0MjM0MjQ0OH0.JjxkhKpR0pf6jeuvvKJzzD-c1QIiCvZlNAkpip-VdiM

{
    "title" : "hello",
    "author" : "John",
    "url" : "www.test.gs",
    "likes" : 100
}

###
DELETE http://localhost:3001/api/blogs/61e42a944d38c031fe24943f
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZTMxMWQ2OGVkODkwMDgxOWRkZGJhOSIsImlhdCI6MTY0MjM0MjQ0OH0.JjxkhKpR0pf6jeuvvKJzzD-c1QIiCvZlNAkpip-VdiM


###
PUT http://localhost:3001/api/blogs/61ddd45f7f701d65f0e0afdd
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZDg0YzE5OGRkYWJlY2QwNmU1MzhmYSIsImlhdCI6MTY0MTkyNzQ5NH0.NBxSqQ6QxJLPnxNrcHB5hdsU6ifxpbvLf02NqxeC91E

{
    "likes" : 500
}
###
GET http://localhost:3003/api/blogs/61ddd45f7f701d65f0e0afdd
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRydW5naG8iLCJpZCI6IjYxZDg0YzE5OGRkYWJlY2QwNmU1MzhmYSIsImlhdCI6MTY0MTkyNzQ5NH0.NBxSqQ6QxJLPnxNrcHB5hdsU6ifxpbvLf02NqxeC91E

###
POST http://localhost3003/api/users
Content-Type: application/json 
{
    "username" : "naiswan",
    "name" : "Trungdepzai",
    "password" : "54321",
    
}

###

POST http://localhost:3003/api/testing/reset
Content-Type: application/json 
